### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by ofarukcaki** [ofarukcaki/Web-Resources#3]

**Comment by islamnurdin** [comment]
Hello,
Please provide a description of the issue.
I will be glad to help. :)

**Comment by ofarukcaki** [comment]
Need to a list of titles at the top of the readme file. For example when you click the **Animation** it should jump to animations section

**Comment by islamnurdin** [comment]
Please see my pull request. You can create links by implementing `[your link text](#Animation)`

**Comment by islamnurdin** [comment]
See the new changes.

**Comment by ofarukcaki** [comment]
Merged #9
